import test from "node:test";
import assert from "node:assert/strict";

import {
  courseLabel,
  extractCourseCode,
  formatISO,
  generateMilestones,
  getHeavyWeekSignal,
  getTaskBucket,
  getTaskUrgency,
  sortByEffortPriority,
  stripExtension,
} from "../lib/tasks/taskHelpers.js";

function dateFromToday(days) {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + days);
  return formatISO(date);
}

test("normalizes course labels from setup data and filenames", () => {
  assert.equal(stripExtension("CMPUT301-syllabus.final.pdf"), "CMPUT301-syllabus.final");
  assert.equal(extractCourseCode("cmput301 fall syllabus"), "CMPUT 301");
  assert.equal(
    courseLabel("course-1", [{ id: "course-1", code: "PSYCO 104", name: "Psychology" }], "fallback"),
    "PSYCO 104",
  );
});

test("places deadlines into the correct planning horizon", () => {
  assert.equal(getTaskBucket(dateFromToday(-1), "active"), "Overdue");
  assert.equal(getTaskBucket(dateFromToday(0), "active"), "Today");
  assert.equal(getTaskBucket(dateFromToday(5), "active"), "This Week");
  assert.equal(getTaskBucket(dateFromToday(10), "active"), "Next Week");
  assert.equal(getTaskBucket(dateFromToday(20), "active"), "Later");
  assert.equal(getTaskBucket(dateFromToday(0), "done"), "Done");
});

test("uses clear urgency labels at deadline boundaries", () => {
  assert.equal(getTaskUrgency(dateFromToday(-1), "active").label, "Overdue");
  assert.equal(getTaskUrgency(dateFromToday(2), "active").label, "Urgent");
  assert.equal(getTaskUrgency(dateFromToday(7), "active").label, "Soon");
  assert.equal(getTaskUrgency(dateFromToday(8), "active").label, "Upcoming");
  assert.equal(getTaskUrgency(dateFromToday(0), "done").label, "Done");
});

test("generates a bounded start plan for major work", () => {
  const dueDate = dateFromToday(28);
  const { milestones, startByDate } = generateMilestones({
    type: "project",
    difficulty: 5,
    dueDate,
  });

  assert.ok(milestones.length >= 2);
  assert.equal(startByDate, milestones[0].date);
  assert.ok(milestones.every((milestone) => milestone.date < dueDate));
  assert.ok(milestones.every((milestone) => milestone.autoGenerated === true));
});

test("surfaces a genuinely heavy upcoming week", () => {
  const tasks = [
    { id: "1", title: "Project", type: "project", difficulty: 5, dueDate: dateFromToday(4), status: "active" },
    { id: "2", title: "Midterm", type: "midterm", difficulty: 5, dueDate: dateFromToday(5), status: "active" },
    { id: "3", title: "Paper", type: "assignment", difficulty: 4, dueDate: dateFromToday(7), status: "active" },
  ];

  const signal = getHeavyWeekSignal(tasks);
  assert.equal(signal.count, 3);
  assert.equal(signal.windowLabel, "the next 7 days");
  assert.ok(signal.effortTotal >= 10);
});

test("effort-aware sorting keeps completed work last", () => {
  const tasks = [
    { id: "done", title: "Done", type: "project", difficulty: 5, dueDate: dateFromToday(0), status: "done" },
    { id: "small", title: "Reading", type: "reading", difficulty: 1, dueDate: dateFromToday(1), status: "active" },
    { id: "large", title: "Final", type: "final", difficulty: 5, dueDate: dateFromToday(3), status: "active" },
  ];

  const sorted = sortByEffortPriority(tasks);
  assert.equal(sorted[0].id, "large");
  assert.equal(sorted.at(-1).id, "done");
});
